// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtFZMJNt7vZau5CIC0Mdt-EPLPJaK_aIc',
    appId: '1:997178301500:web:120826a61a914085bf3739',
    messagingSenderId: '997178301500',
    projectId: 'msw-hd121',
    authDomain: 'msw-hd121.firebaseapp.com',
    storageBucket: 'msw-hd121.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYWbgaLrFyzs5K7spwfPDYotSW6b23gcM',
    appId: '1:997178301500:android:914b65be8bd96dd8bf3739',
    messagingSenderId: '997178301500',
    projectId: 'msw-hd121',
    storageBucket: 'msw-hd121.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyV1Cxizq8piypxbawHgsjHXyR1fHFGOQ',
    appId: '1:997178301500:ios:5cccf1588568dda3bf3739',
    messagingSenderId: '997178301500',
    projectId: 'msw-hd121',
    storageBucket: 'msw-hd121.appspot.com',
    iosClientId: '997178301500-ha48mob6gdgiteo0pi9nusfh70385tf2.apps.googleusercontent.com',
    iosBundleId: 'codex.mswhd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyV1Cxizq8piypxbawHgsjHXyR1fHFGOQ',
    appId: '1:997178301500:ios:5cccf1588568dda3bf3739',
    messagingSenderId: '997178301500',
    projectId: 'msw-hd121',
    storageBucket: 'msw-hd121.appspot.com',
    iosClientId: '997178301500-ha48mob6gdgiteo0pi9nusfh70385tf2.apps.googleusercontent.com',
    iosBundleId: 'codex.mswhd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtFZMJNt7vZau5CIC0Mdt-EPLPJaK_aIc',
    appId: '1:997178301500:web:958dfdeefe6cd5f8bf3739',
    messagingSenderId: '997178301500',
    projectId: 'msw-hd121',
    authDomain: 'msw-hd121.firebaseapp.com',
    storageBucket: 'msw-hd121.appspot.com',
  );
}
